site_name: NoQL
repo_url: https://github.com/synatic/noql
repo_name: synatic/noql
copyright: Copyright &copy; 2023 <a href="https://synatic.com">Synatic Inc.</a>
theme:
  name: material
  custom_dir: docs/overrides/
  logo: assets/synatic.svg
  favicon: assets/synatic-favicon.jpeg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - content.code.copy
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    # - toc.integrate
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode
    # # Palette toggle for light mode
    # - media: "(prefers-color-scheme: light)"
    #   scheme: default
    #   toggle:
    #     icon: material/weather-sunny
    #     name: Switch to dark mode
    # # Palette toggle for dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   toggle:
    #     icon: material/weather-night
    #     name: Switch to light mode
extra:
  analytics:
    provider: google
    property: G-7VEMMQEFLN
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/datasynatic
      name: Synatic on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/synatic/noql
      name: NoQL on Github
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/15815217/
      name: Synatic on Linkedin
extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/default.min.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/ace/1.15.2/ace.js
  - javascripts/noql/index.js
  - javascripts/playground/nodeQueryConstructor.js
  - javascripts/playground/shellQueryConstructor.js
  - javascripts/playground/playground.js
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
nav:
  - Home: index.md
  - SQL Syntax:
      - Introduction: sql-syntax/introduction.md
      - Objects: sql-syntax/objects.md
      - Arrays: sql-syntax/arrays.md
      - Where Clause: sql-syntax/where-clause.md
      - Order By Clause: sql-syntax/order-by-clause.md
      - Joins: sql-syntax/joins.md
      - Aggregates: sql-syntax/aggregates.md
      - Comparison Operators: sql-syntax/comparison-operators.md
      - Field Functions: sql-syntax/field-functions.md
      - String Functions: sql-syntax/string-functions.md
      - Date Functions: sql-syntax/date-functions.md
      - Mathematical Operators: sql-syntax/mathematical-operators.md
      - Mathematical Functions: sql-syntax/mathematical-functions.md
      - Conversion Functions: sql-syntax/conversion-functions.md
      - Window Functions: sql-syntax/window-functions.md
      - Limits and Offsets: sql-syntax/limits-and-offsets.md
      - Union: sql-syntax/union.md
      - Pivot And Unpivot: sql-syntax/pivot-unpivot.md
  - Playground: playground/index.md
  - JS Library:
      - Getting Started: js-library/getting-started.md
      - API: js-library/api-reference.md
