name: "Build"

on:
  push:
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:7.0
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      # Skip post-install scripts here, as a malicious
      # script could steal NODE_AUTH_TOKEN.
      - name: Install NPM dependencies
        run: npm install --ignore-scripts
      - name: Audit packages
        run: npm audit --audit-level=high --omit=dev
      - name: Run linting
        run: npm run lint
      - name: Run tests
        run: npm run test-ci
      - name: Run NPM pack
        run: npm pack